source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.2'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem "versionist"
gem 'pry'
gem 'pry-rails'
gem 'powder'
gem 'lorem_ipsum_amet'

group :test do
  gem "rspec-rails"
end

